import jwt from '@fastify/jwt';
import type { FastifyInstance } from 'fastify';
import type { User, Organization } from '@brain/shared';

export interface JWTPayload {
  userId: string;
  organizationId: string;
  email: string;
  role: string;
}

export async function setupJWT(app: FastifyInstance) {
  const secret = process.env.NEXTAUTH_SECRET || 'change-me-in-production';

  await app.register(jwt, {
    secret,
  });

  app.decorate('authenticate', async function (request, reply) {
    try {
      await request.jwtVerify();
    } catch (err) {
      reply.send(err);
    }
  });
}

export function generateToken(payload: JWTPayload): string {
  // Token will be generated by Fastify JWT plugin
  return '';
}

declare module 'fastify' {
  interface FastifyInstance {
    authenticate: (request: any, reply: any) => Promise<void>;
  }

  interface FastifyRequest {
    user?: JWTPayload;
  }
}
